### ISSUE TITLE
[p0] Add regression tests in github actions

### ISSUE THREAD

**Issue by sahel-sh** [castorini/rank_llm#245]
We need to add a selected subset of 2crs as github actions to have regression tests to avoid regressions like https://github.com/castorini/rank_llm/pull/242#issuecomment-2988495424.
- We should run them before releases, and before risky PRs (large PRs, lots of refactoring, etc).
- It can be a self-hosted runner: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners or github-hosted large runners with T4 GPU: https://docs.github.com/en/enterprise-cloud@latest/actions/using-github-hosted-runners/using-larger-runners/about-larger-runners
  -  (what's the cost estimate?, what can we run with T4?)

**Comment by clides** [comment]
I'm working on this issue

**Comment by clides** [comment]
This is a proof-of-concept of creating a temp conda env to install the required rankllm packages and then running predefined regression scripts

```yml
env:
  CONDA_BASE: "/opt/homebrew/Caskroom/miniconda/base"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Install dependencies
        shell: bash
        run: |
          source "$CONDA_BASE/etc/profile.d/conda.sh"
          conda create -n WorkflowTest python=3.10 -y
          conda activate WorkflowTest
          
          conda install -y numpy
          conda list

          python -c "import numpy; print(f'NumPy version: {numpy.__version__}')"

          conda deactivate
          conda env remove -n WorkflowTest -y
```
